all: all-Calculus all-GnA

clean:
	make -C Calculus clean
	make -C GnA clean

dist-clean:
	make -C Calculus dist-clean
	make -C GnA dist-clean



all-Calculus:
	make -C Calculus

all-GnA:
	make -C GnA

