
all: all-AnP/Uni-RG-AnP-Reference_Work_1

clean:
	make -C AnP/Uni-RG-AnP-Reference_Work_1 clean
	make -C Prog/RefWork1 clean

dist-clean:
	make -C AnP/Uni-RG-AnP-Reference_Work_1 dist-clean
	make -C Prog/RefWork1 dist-clean

all-AnP/Uni-RG-AnP-Reference_Work_1:
	make -C AnP/Uni-RG-AnP-Reference_Work_1
	
all-Prog/RefWork1:
	make -C Prog/RefWork1
